ai_confidence_threshold: 0.8
ai_source: blip
default_version: 1
input_folder: Z:/Baby Fairs 2024
log_file: Z:/Baby Fairs 2024/output/rename_log.csv
output_dnu: output/dnu/
output_renamed: Z:/Baby Fairs 2024/output
output_review: output/review/
publish_values:
- 'yes'
- y
- 'true'
use_ai: false
version_format: _v{n}
